### PR TITLE
Enable artefact publishing configuration

### PR DESCRIPTION
**Pull request by kristofa**
Configure project to support publishing of
snapshots and release artefacts according to
instructions found here:
http://central.sonatype.org/pages/apache-maven.html

### CODE REVIEW

**Comment by kristofa** [comment]
When I try to deploy snapshot I get 

```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy (injected-nexus-deploy) on project zipkin-java-server: Failed to deploy artifacts: Could not transfer artifact io.zipkin:zipkin-java:pom.asc:0.1.0-20150922.191000-1 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Access denied to: https://oss.sonatype.org/content/repositories/snapshots/io/zipkin/zipkin-java/0.1.0-SNAPSHOT/zipkin-java-0.1.0-20150922.191000-1.pom.asc, ReasonPhrase: Forbidden. -> [Help 1]
```
but that is probably because I have no access yet. Waiting for [https://issues.sonatype.org/browse/OSSRH-16669](https://issues.sonatype.org/browse/OSSRH-16669).

It would be good if somebody else can try deploying.

**Comment by kristofa** [comment]
pr for issue #7

**Comment by kristofa** [comment]
Build fails on Travis because of gpg not available. I'll try to implement a separate profile for doing gpg.

**Comment by kristofa** [comment]
@adriancole I got access for publishing to and snapshot deploy seems to work. See [https://oss.sonatype.org/content/repositories/snapshots/io/zipkin/](https://oss.sonatype.org/content/repositories/snapshots/io/zipkin/).

To reproduce:

```
./mvnw clean deploy -P release
```

**Comment by kristofa** [comment]
For it to work on your machine you need to update your `settings.xml` to add something like

```
<profiles>
    <profile>
      <id>ossrh</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <gpg.executable>gpg</gpg.executable>
        <gpg.passphrase>your_passphrase</gpg.passphrase>
      </properties>
    </profile>
  </profiles>
  <servers>
    <server>
      <id>ossrh</id>
      <username>sonatype_user</username>
      <password>sonatype_pwd</password>
    </server>
</servers>
```

This is also outlined in [http://central.sonatype.org/pages/apache-maven.html](http://central.sonatype.org/pages/apache-maven.html)

**Comment by adriancole** [comment]
Thank you *so* much!

**Pull request merged**
