### PR TITLE
Maven central sync

### PR DESCRIPTION
**Pull request by abesto**
This is both nice in itself, and opens the way for #155

### CODE REVIEW

**Comment by abesto** [comment]
Hm, in its current state will the central sync run for SNAPSHOT releases on Travis? (Can investigate, but if someone knows this by heart, that's easier :))

**Comment by adriancole** [comment]
this branch looks to have code to build the plugin, but none of the poms
are setup to run it, so I think it is safe to merge if that's the concern.

**Comment by adriancole** [comment]
build was failing due to a missing travis statement. basically travis was using an old version of maven instead of using the wrapper. fingers crossed!

**Comment by adriancole** [comment]
I've excluded this from being published, since it is internal use. We can always change that later.

**Pull request merged**
