### PR TITLE
Updates to Brave 3.6 and makes self-tracing optional

### PR DESCRIPTION
**Pull request by adriancole**
This updates to latest Brave, and makes it possible to configure
self-tracing.

Self tracing exists to help troubleshoot performance of the zipkin-server.

When Brave dependencies are in the classpath, and `zipkin.self-tracing.enabled=true`,
Zipkin will self-trace calls to the api.

[yaml configuration](zipkin-server/src/main/resources/zipkin-server.yml) binds the following environment variables to spring properties:

Variable | Property | Description
--- | --- | ---
SELF_TRACING_ENABLED | zipkin.self-tracing.enabled | Set to false to disable self-tracing. Defaults to true
SELF_TRACING_FLUSH_INTERVAL | zipkin.self-tracing.flush-interval | Interval in seconds to flush self-tracing data to storage. Defaults to 1

### CODE REVIEW

**Comment by adriancole** [comment]
Before this change, those using docker couldn't disable self-tracing eventhough those making custom builds could (by removing the brave dependency)

**Comment by adriancole** [comment]
build failures are unrelated (due to adaptive sampler) and will be solved by #167

**Comment by eirslett** [comment]
How about calling them `SELF_TRACING_ENABLED` and `SELF_TRACING_FLUSH_INTERVAL`?

**Comment by adriancole** [comment]
had that in my history, so I guess that's 2 votes :P

**Comment by adriancole** [comment]
@eirslett done

**Comment by eirslett** [comment]
:shipit:

**Pull request merged**
