### PR TITLE
Adds tracing for Api and JDBC layers

### PR DESCRIPTION
**Pull request by adriancole**
This adds a Brave tracer, adding Server Receive and Server Send annotations for `zipkin-query`.

This uses JOOQ to add to Client Send and Client Receive traces for the service named `zipkin-jdbc`

### CODE REVIEW

**Comment by adriancole** [comment]
cc @dsyer @spencergibb @kristofa

**Comment by adriancole** [comment]
Here's the trace depth now

screen shot 2015-10-09 at 1 24 30 pm

**Comment by adriancole** [comment]
Here's an example showing the actual SQL query

screen shot 2015-10-09 at 1 29 15 pm

**Comment by kristofa** [comment]
Nice! We could add JOOQ support (with read and write) to brave.

**Comment by adriancole** [comment]
@kristofa yep especially now that zipkin-java no longer does any writes to the database!

**Comment by adriancole** [comment]
oh wait.. it does, but yeah in general, it would be a cool feature, and quite easy to configure

**Pull request merged**
