### PR TITLE
Basic implementation with in-memory storage

### PR DESCRIPTION
**Pull request by adriancole**
Basic implementation with in-memory storage

* Multi-module structure for Java 8 with Maven Wrapper (`./mvnw`)
  * source and javadoc jars are produced
  * javadoc excludes packages marked internal
* CONTRIBUTING.md explains code format and contribution agreement
  * Missing license header will break compilation
* Thrift classes are annotated with swift, and generated by auto-value
  * Note runtime is patched until facebook/swift issue 274 is merged.
* Tests use JUnit and AssertJ

The ZipkinServer works, albeit in-memory:
```bash
$ du -k zipkin-java-server/target/zipkin-server 
10056	zipkin-java-server/target/zipkin-server
$ zipkin-java-server/target/zipkin-server 
Sep 07, 2015 5:52:56 PM io.airlift.log.Logger info
INFO: started transport thrift:9410 (:9410)
Sep 07, 2015 5:52:56 PM io.airlift.log.Logger info
INFO: started transport thrift:9411 (:9411)
```

Further work is needed to port backends and handle time skew adjustment.
We can do this collaboratively vs a forever-branch.

### CODE REVIEW

**Comment by adriancole** [comment]
updated description and added auto-license header thing

**Comment by adriancole** [comment]
I ran `io.zipkin.api.ZipkinRule.main` and `bin/tracegen` and `bin/web` worked from the scala project. Needs lots of work, but it is a milestone.

**Comment by adriancole** [comment]
added zipkin-java-api package, compiled as java7 bytecode with no deps except swift annotation jar.

**Comment by adriancole** [comment]
trimmed according to latest zipkin thrifts

**Comment by adriancole** [comment]
The ZipkinServer works, albeit in-memory:
```bash
$ du -k zipkin-java-server/target/zipkin-server 
10056	zipkin-java-server/target/zipkin-server
$ zipkin-java-server/target/zipkin-server 
Sep 07, 2015 5:52:56 PM io.airlift.log.Logger info
INFO: started transport thrift:9410 (:9410)
Sep 07, 2015 5:52:56 PM io.airlift.log.Logger info
INFO: started transport thrift:9411 (:9411)
```

Further work is needed to port backends and handle time skew adjustment.
We can do this collaboratively vs a forever-branch. PTAL!

**Comment by spencergibb** [comment]
:+1: to merge and work on master.

**Comment by kristofa** [comment]
:thumbsup: nice work! I might copy/steal the maven wrapper for brave ;) I'm unable to test the ZipkinServer integration with brave right now but will do next week.

I like the approach using swift as you explained me before. If we have a first release we can port libraries like brave over to zipkin-java!

**Pull request merged**
