### PR TITLE
Adds WIP JDBC backend

### PR DESCRIPTION
**Pull request by adriancole**
Adds an experimental MySQL backend which uses a simpler table structure
than upstream. It is simpler as it keeps a single table for annotations
regardless of whether they are "binary" or not.

While not yet hooked up, this passes all tests in SpanStoreSpec, and I
also succesfully deployed it to EC2, targetting an RDS MySQL instance.

### CODE REVIEW

**Comment by adriancole** [comment]
cc @dsyer @spencergibb @jfeltesse-mdsol I'm inclined to merge and progress eventhough I've not woven in the SpanStoreSpec nicely (and/or have the impl testing against an in-memory or travis based mysql, yet). thoughts?

**Comment by dsyer** [comment]
You mean the tests pass but not yet automated? Sounds good to me.

**Comment by adriancole** [comment]
Exactly. I ran them manually as they need to point to a MySQL instance. I
can follow-up with a Travis related change that runs them automatically.

**Comment by spencergibb** [comment]
:+1:

**Pull request merged**
